### PR TITLE
Support Anki 2.1

### PR DESCRIPTION
**Pull request by 71e6fd52**
Not use Anki 2.1 configuration system yet.

### CODE REVIEW

**Comment by eshapard** [comment]
OK, I don't use version 2.1, so I can't test this out, but I'll go ahead and merge.
Thanks for putting in the work to make this change!

**Comment by Sabicool** [comment]
Doesn't seem to work? I tried installing it using the 954979168 code and here is the error that came up:
image

**Comment by eshapard** [comment]
OK, looks like the ankiweb file might be missing the logging files. I'll 
look into that.

Try installing the version on github for now.

Excerpts from Sabicool's message of May 25, 2019 7:41 am:

**Comment by eshapard** [comment]
Can you check that there's a logging subdirectory under 
addons21/954979168 ? The zip file I uploaded seems to have it.

I don't have version 2.1, so there's not a whole lot of troubleshooting 
I can do.

Hopefully user 71e6fd52, who created the pull request will help out.

Excerpts from Sabicool's message of May 25, 2019 7:41 am:

**Comment by Sabicool** [comment]
Same problem unless I'm doing something wrong
image

**Comment by eshapard** [comment]
The addon isn't finding handlers.py in the logging subdirecory. Do 
that subdirectory and fil exist? 
(/addons21/954979168/logging/handlers.py)

Excerpts from Sabicool's message of May 26, 2019 4:53 am:

**Comment by 71e6fd52** [comment]
@Sabicool track in new issue #69

**Pull request merged**
